- name : Configure nginx site
  block:
  - name: Remove default site
    ansible.builtin.file:
      path: /etc/nginx/sites-enabled/default
      state: absent
  - name: Create nginx site configuration
    template:
      src: site.conf.j2
      dest: /etc/nginx/sites-available/site.conf
      owner: root
      group: root
      mode: 0644
      force: yes
  - name: Enable nginx site
    ansible.builtin.file:
      src: /etc/nginx/sites-available/site.conf
      dest: /etc/nginx/sites-enabled/site.conf
      owner: root
      group: root
      state: link
    notify: restart nginx
  become: true